[general]
import= [
	"~/.config/alacritty/themes/themes/midnight_haze.toml"
]

[font]
size = 12.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }  

[window]
opacity = 0.9 
startup_mode= "Maximized"
title= "Tenkaism"
